-- Optipeople Docs — share tokens for QR / public read-only access.
--
-- A share token is a random opaque secret that lives in a URL like
-- /s/<token>. Knowing the token grants read access to a scope:
--   * folder-scoped: the named folder and everything under it
--   * account-scoped: everything in the account (folder_id is null)
--
-- Tokens are soft-deleted via revoked_at so we keep an audit trail.

create table doc.share_tokens (
  id          uuid primary key default gen_random_uuid(),
  -- 32 char random secret. URL-safe alphabet, generated by the
  -- application layer (crypto.randomUUID + base64url) before insert.
  token       text not null unique,
  account_id  text not null,
  -- Null means the token covers the whole account.
  folder_id   uuid references doc.folders (id) on delete cascade,
  label       text,
  created_by  text not null,
  created_at  timestamptz not null default now(),
  revoked_at  timestamptz
);

-- Lookup-by-token must be cheap and only return active tokens.
create index share_tokens_token_idx
  on doc.share_tokens (token)
  where revoked_at is null;

create index share_tokens_account_idx on doc.share_tokens (account_id);
create index share_tokens_folder_idx  on doc.share_tokens (folder_id);

-- Same invariant as folder_machines and files: if a folder is named,
-- it must live in the same account as the token.
create function doc.assert_share_token_account_match() returns trigger as $$
begin
  if new.folder_id is not null then
    if (select account_id from doc.folders where id = new.folder_id) <> new.account_id then
      raise exception 'share_tokens.account_id must match the folder''s account_id';
    end if;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger share_tokens_account_match
  before insert or update on doc.share_tokens
  for each row execute function doc.assert_share_token_account_match();

alter table doc.share_tokens enable row level security;
-- Backend (service role) is the security boundary, same as the rest
-- of the doc schema. No RLS policies — anon/authenticated have no
-- access; service role bypasses.

grant all on doc.share_tokens to service_role;
;
